// <auto-generated />
namespace Hitcher.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class added_route_start_time : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_route_start_time));
        
        string IMigrationMetadata.Id
        {
            get { return "201505122019124_added_route_start_time"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
