// <auto-generated />
namespace Hitcher.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RouteRecurrency_Added_Right : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RouteRecurrency_Added_Right));
        
        string IMigrationMetadata.Id
        {
            get { return "201505151931244_RouteRecurrency_Added_Right"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
