// <auto-generated />
namespace Hitcher.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Route_Recurrency_modified : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Route_Recurrency_modified));
        
        string IMigrationMetadata.Id
        {
            get { return "201505140758047_Route_Recurrency_modified"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
